name: StrakaTennis
favicon: null
layout_spectrum: 0.3060708
typography_spectrum: 0.1863406
title: StrakaTennis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#333333'
    - '#e2e2e2'
    - '#686767'
    - '#a29e9f'
  brandStrength: 0.9375
  lightness: 0.9688027
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
